[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.basics]
src = "src/basics"
test = "src/basics/tests"

[profile.inter]
src = "src/intermediate"
test = "src/intermediate/tests"